project:
  type: website

website:
  title: "Quarto Blog Demo" 
  navbar:
    right:
      - blog.qmd # Change to blog.qmd here
      - icon: github
        href: https://github.com/AlbertRapp
      - icon: twitter
        href: https://twitter.com/rappa753
      - icon: youtube
        href: https://www.youtube.com/user/Alfrodo123
        
format:
  html:
    theme: default

editor: source

